import { StyleSheet } from "react-native"


const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F5F5",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: "#322D70",
  },
  backButton: {
    padding: 4,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  scrollContent: {
    flex: 1,
  },
  groupHeaderCard: {
    backgroundColor: "#FFFFFF",
    margin: 16,
    marginBottom: 12,
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    gap: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  groupHeaderPhotoWrapper: {
    position: "relative",
  },
  groupHeaderPhoto: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  groupHeaderPhotoPlaceholder: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#E0E7FF",
    justifyContent: "center",
    alignItems: "center",
  },
  groupHeaderPhotoInitial: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#322D70",
  },
  groupHeaderPhotoEditBadge: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: "#322D70",
    borderRadius: 12,
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#FFFFFF",
  },
  groupHeaderPhotoEditIcon: {
    fontSize: 11,
  },
  tabBar: {
    flexDirection: "row",
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 12,
    overflow: "hidden",
  },
  tabItem: {
    flex: 1,
    paddingVertical: 14,
    alignItems: "center",
    borderBottomWidth: 3,
    borderBottomColor: "transparent",
  },
  tabItemActive: {
    borderBottomColor: "#322D70",
  },
  tabItemText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#9CA3AF",

  },
  tabItemTextActive: {
    color: "#322D70",
  },
  infoCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  infoCardTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#322D70",
    marginBottom: 8,
  },
  infoCardText: {
    fontSize: 14,
    color: "#475569",
    fontWeight: "600",
  },
  memberRow: {
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  memberName: {
    fontSize: 14,
    color: "#1E293B",
  },
  groupSummaryCard: {
    marginTop: 8,
    marginBottom: 16,

  },
  groupSummaryTop: {
    flexDirection: "row",
    alignItems: "stretch",
    marginBottom: 12,
  },
  groupSummaryPhoto: {
    width: 120,
    borderRadius: 16,
    backgroundColor: "#E0E7FF",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    marginRight: 16,
  },
  groupSummaryImage: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  groupSummaryInitial: {
    fontSize: 40,
    fontWeight: "bold",
    color: "#322D70",
  },
  groupSummaryInfo: {
    flex: 1,
    justifyContent: "space-between",
  },
  bestMemberRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 12,
    padding: 8,
        shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
    marginBottom: 8,
  },
  bestMemberAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#E0E7FF",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    marginRight: 12,
    marginLeft: 12,
  },
  bestMemberAvatarImage: {
    width: 36,
    height: 36,
  },
  bestMemberAvatarText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#322D70",
  },
  bestMemberText: {
    flex: 1,
    borderLeftWidth: 1,
    borderLeftColor: "#D9D9D9",
    paddingLeft: 12,
  },  
  bestMemberLabel: {
    fontSize: 13,
    color: "#6881BA",
    fontWeight: "bold",
  },
  bestMemberValue: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#322D70",
  },
  participantsButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  participantsIcon: {
    fontSize: 20,
    marginRight: 10,
  },
  participantsText: {
    flex: 1,
    fontSize: 14,
    fontWeight: "bold",
    color: "#6881BA",
    marginLeft: 12,
  },
  participantsChevron: {
    fontSize: 22,
    color: "#6881BA",
    fontWeight: "bold",
  },
  highlightSection: {
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 16,
  },
  highlightTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#322D70",
    marginBottom: 4,
  },
  highlightSubtitle: {
    fontSize: 13,
    color: "#6881BA",
    marginBottom: 16,
  },
  periodToggleContainer: {
    marginBottom: 16,
    alignItems: "center",
    backgroundColor: "#C3CDE3",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  periodToggle: {
    flexDirection: "row",
    borderRadius: 10,
    padding: 4,
    width: "100%",
  },
  periodToggleButton: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: "center",
  },
  periodToggleButtonActive: {
    backgroundColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  periodToggleText: {
    fontSize: 14,
    fontWeight: "900",
    color: "#322D70",
  },
  periodToggleTextActive: {
    color: "#322D70",
  },
  periodDateLabel: {
    backgroundColor: "white",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    borderBottomEndRadius: 8,
    borderBottomLeftRadius: 8,
  },
  sectionHeaderRow: {
    marginBottom: 12,
  },
  feedContainer: {
    flex: 1,
    minHeight: 400,
  },
  section: {
    marginHorizontal: 16,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#322D70",
    marginBottom: 12,
  },
  groupAvatarLarge: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#E0E7FF",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    marginBottom: 12,
  },
  groupImage: {
    width: "100%",
    height: "100%",
  },
  groupName: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#322D70",
    marginBottom: 4,
    textAlign: "center",
  },
  groupMembers: {
    fontSize: 14,
    color: "#6881BA",
    textAlign: "center",
  },
  descriptionSection: {
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#6881BA",
    marginBottom: 8,
  },
  groupDescription: {
    fontSize: 16,
    color: "#475569",
    lineHeight: 24,
  },
  codeSection: {
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
    marginTop: 16,
  },
  codeContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  codeBox: {
    flex: 1,
    backgroundColor: "#F8FAFC",
    flexDirection: "row",
    justifyContent: "space-between",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#6881BA",
    alignItems: "center",
  },
  codeText: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#322D70",
    letterSpacing: 4,
  },
  codeActions: {
    flexDirection: "row",
  },
  codeActionButton: {
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
  },
  codeHelper: {
    fontSize: 12,
    color: "#6881BA",
    marginTop: 8,
    lineHeight: 16,
  },
  statsCard: {
    backgroundColor: "#322D70",
    marginHorizontal: 16,
    marginBottom: 12,
    borderRadius: 16,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  statsTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 16,
    textAlign: "center",
  },
  statsGrid: {
    flexDirection: "row",
    alignItems: "center",
  },
  statItem: {
    flex: 1,
    alignItems: "center",
  },
  statDivider: {
    width: 1,
    height: 40,
    backgroundColor: "rgba(255, 255, 255, 0.3)",
  },
  statValue: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 13,
    color: "rgba(255, 255, 255, 0.8)",
  },
  rankingCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    paddingLeft: 12,
    paddingRight: 12,
    paddingVertical: 8,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 4,
    elevation: 2,
  },
  rankingAvatarWrapper: {
    position: "relative",
    marginRight: 16,
  },
  rankingAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#E0E7FF",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  rankingAvatarImage: {
    width: 36,
    height: 36,
  },
  rankingAvatarText: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#322D70",
  },
  rankingMedalBadge: {
    position: "absolute",
    bottom: -6,
    left: -6,
    fontSize: 18,
  },
  rankingName: {
    flex: 1,
    fontSize: 16,
    fontWeight: "bold",
    color: "#322D70",
  },
  rankingTimeColumn: {
    alignItems: "flex-start",
  },
  rankingTimeLabel: {
    fontSize: 12,
    color: "#6881BA",
    fontWeight: "800",
    marginBottom: 2,
  },
  rankingTimeValue: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#322D70",
  },
  rankingTimeNoData: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#94A3B8",
  },
  rankingSubtitle: {
    fontSize: 13,
    color: "#6881BA",
    marginBottom: 12,
  },
  loadingContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 20,
  },
  loadingText: {
    fontSize: 14,
    color: "#6881BA",
    marginLeft: 12,
  },
  noDataText: {
    fontSize: 12,
    color: "#94A3B8",
    fontStyle: "italic",
  },
  noDataBadge: {
    minWidth: 60,
    alignItems: "flex-end",
  },
  noDataBadgeText: {
    fontSize: 18,
    color: "#94A3B8",
  },
  emptyRankingContainer: {
    paddingVertical: 32,
    alignItems: "center",
  },
  emptyRankingText: {
    fontSize: 14,
    color: "#6881BA",
  },
  actionButton: {
    flexDirection: "row",
    backgroundColor: "#322D70",
    marginHorizontal: 16,
    marginTop: 8,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
  },
  actionButtonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginRight: 8,
  },
  codeActionIcon: {
    fontSize: 20,
  },
  criterionPill: {
    alignSelf: "flex-start",
    backgroundColor: "#72C3E0",
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 16,
    marginTop: 8,
  },
  criterionPillText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "600",
  },
  infoSectionTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#6881BA",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginTop: 16,
    marginBottom: 8,
    marginHorizontal: 4,
  },
  leaveGroupButton: {
    backgroundColor: "#E53935",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    marginBottom: 8,
  },
  leaveGroupButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },
  participantsModalContent: {
    maxHeight: "80%",
  },
  participantsList: {
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  participantRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  participantAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#E0E7FF",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    marginRight: 12,
  },
  participantAvatarImage: {
    width: 44,
    height: 44,
  },
  participantAvatarText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#322D70",
  },
  participantInfo: {
    flex: 1,
  },
  participantName: {
    fontSize: 15,
    fontWeight: "600",
    color: "#1E293B",
    marginBottom: 2,
  },
  participantAdminBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#FFF7ED",
    borderRadius: 8,
    paddingVertical: 2,
    paddingHorizontal: 8,
  },
  participantAdminBadgeText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#C2410C",
  },
  participantMenuButton: {
    padding: 8,
    marginLeft: 4,
  },
  participantMenuDots: {
    fontSize: 22,
    color: "#6881BA",
    fontWeight: "bold",
    letterSpacing: 1,
  },
  fabButton: {
    position: "absolute",
    bottom: 24,
    right: 24,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#322D70",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  fabButtonText: {
    fontSize: 32,
    fontWeight: "300",
    color: "#FFFFFF",
    lineHeight: 32,
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "85%",
    paddingBottom: 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#322D70",
  },
  modalBody: {
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#322D70",
    marginBottom: 12,
  },
  activityTypesScroll: {
    marginBottom: 24,
  },
  activityTypeChip: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: "#F1F5F9",
    marginRight: 8,
    borderWidth: 2,
    borderColor: "transparent",
  },
  activityTypeChipActive: {
    backgroundColor: "#E0E7FF",
    borderColor: "#322D70",
  },
  activityTypeEmoji: {
    fontSize: 18,
    marginRight: 6,
  },
  activityTypeLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: "#64748B",
  },
  activityTypeLabelActive: {
    color: "#322D70",
    fontWeight: "600",
  },
  textInput: {
    backgroundColor: "#F8FAFC",
    borderRadius: 12,
    padding: 16,
    fontSize: 15,
    color: "#1E293B",
    minHeight: 120,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    marginBottom: 20,
  },
  modalFooter: {
    flexDirection: "row",
    paddingHorizontal: 20,
    paddingTop: 16,
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: "#F1F5F9",
    alignItems: "center",
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#64748B",
  },
  postButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: "#322D70",
    alignItems: "center",
    justifyContent: "center",
  },
  postButtonDisabled: {
    backgroundColor: "#94A3B8",
    opacity: 0.6,
  },
  postButtonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  imagePreviewContainer: {
    position: "relative",
    marginBottom: 20,
    borderRadius: 12,
    overflow: "hidden",
  },
  imagePreview: {
    width: "100%",
    height: 200,
    borderRadius: 12,
  },
  removeImageButton: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    borderRadius: 20,
    width: 32,
    height: 32,
    justifyContent: "center",
    alignItems: "center",
  },
  addImageButton: {
    backgroundColor: "#F8FAFC",
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#E2E8F0",
    borderStyle: "dashed",
    paddingVertical: 32,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  addImageIcon: {
    fontSize: 48,
  },
  addImageText: {
    fontSize: 14,
    color: "#6881BA",
    fontWeight: "600",
    marginTop: 8,
  },
  managementModalContent: {
    maxHeight: "70%",
  },
  managementOptions: {
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  managementOption: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 16,
    backgroundColor: "#F8FAFC",
    borderRadius: 12,
    marginBottom: 12,
  },
  managementOptionIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
  },
  managementOptionEmoji: {
    fontSize: 24,
  },
  managementOptionContent: {
    flex: 1,
  },
  managementOptionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#322D70",
    marginBottom: 4,
  },
  managementOptionDescription: {
    fontSize: 13,
    color: "#6881BA",
  },
  managementDivider: {
    height: 1,
    backgroundColor: "#E5E7EB",
    marginVertical: 16,
  },
  managementSectionTitle: {
    fontSize: 12,
    fontWeight: "600",
    color: "#6881BA",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 12,
    paddingHorizontal: 16,
  },
  updatingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    justifyContent: "center",
    alignItems: "center",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  updatingText: {
    fontSize: 14,
    color: "#322D70",
    marginTop: 12,
    fontWeight: "600",
  },
  infoCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  groupTypeOption: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    marginBottom: 10,
    backgroundColor: "#F8FAFC",
  },
  groupTypeOptionActive: {
    borderColor: "#322D70",
    backgroundColor: "#E0E7FF",
  },
  groupTypeRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#94A3B8",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  groupTypeRadioActive: {
    borderColor: "#322D70",
  },
  groupTypeRadioDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#322D70",
  },
  groupTypeOptionText: {
    fontSize: 15,
    color: "#64748B",
  },
  groupTypeOptionTextActive: {
    color: "#322D70",
    fontWeight: "600",
  },
  datePreviewText: {
    marginTop: 12,
    fontSize: 14,
    color: "#322D70",
    fontWeight: "600",
    textAlign: "center",
    textTransform: "capitalize",
  },
})

export default styles